### ISSUE TITLE
Exception when tuning weights with libsvm

### ISSUE THREAD

**Issue by mcchong** [fracpete/multisearch-weka-package#17]
Hi, I'm running version 2016.5.25, and am hitting the following exception:

`+ java weka.classifiers.meta.MultiSearch -E PRC -t train.arff -W weka.classifiers.functions.LibSVM -d LibSVM.model -log-file LibSVM.log -search 'weka.core.setupgenerator.MathParameter -property classifier.cost -min -3 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.MathParameter -property classifier.gamma -min -2 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.ListParameter -property classifier.weights -list "\"1 100\" \"1 10\" \"1 1\""'
Zero Weights processed. Default weights will be used
java.beans.IntrospectionException: Method not found: isClassifier
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:107)
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
    at weka.core.PropertyPath.find(PropertyPath.java:386)
    at weka.core.SetupGenerator.setup(SetupGenerator.java:592)
    at weka.classifiers.meta.multisearch.DefaultEvaluationTask.doRun(DefaultEvaluationTask.java:83)
    at weka.classifiers.meta.multisearch.AbstractEvaluationTask.run(AbstractEvaluationTask.java:99)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.beans.IntrospectionException: Method not found: isClassifier
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:107)
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
    at weka.core.PropertyPath.find(PropertyPath.java:386)
    at weka.core.SetupGenerator.setup(SetupGenerator.java:592)
    at weka.classifiers.meta.multisearch.DefaultEvaluationTask.doRun(DefaultEvaluationTask.java:83)
    at weka.classifiers.meta.multisearch.AbstractEvaluationTask.run(AbstractEvaluationTask.java:99)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.beans.IntrospectionException: Method not found: isClassifier
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:107)
    at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
    at weka.core.PropertyPath.find(PropertyPath.java:386)
    at weka.core.SetupGenerator.setup(SetupGenerator.java:592)
    at weka.classifiers.meta.multisearch.DefaultEvaluationTask.doRun(DefaultEvaluationTask.java:83)
    at weka.classifiers.meta.multisearch.AbstractEvaluationTask.run(AbstractEvaluationTask.java:99)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
....*
optimization finished, #iter = 4808
nu = 0.23357145684034458
obj = -554.5871835474204, rho = -0.805166553228126
`

The issue appears to be with tuning the weight parameters.  Perhaps I am not escaping the list correctly?

**Comment by fracpete** [comment]
Drop the `classifier.` prefix, as you're changing the parameters of LibSVM directly and not LibSVM inside a `FilteredClassifier`. Here is my command-line (excluding classifier and training set):

```
-E PRC -W weka.classifiers.functions.LibSVM -d LibSVM.model -log-file LibSVM.log -search "weka.core.setupgenerator.MathParameter -property cost -min -3 -max 2 -step 1.0 -base 10.0 -expression \"pow(BASE, I)\"" -search "weka.core.setupgenerator.MathParameter -property gamma -min -2 -max 2 -step 1.0 -base 10.0 -expression \"pow(BASE, I)\"" -search "weka.core.setupgenerator.ListParameter -property weights -list \"\\"1 100\\" \\"1 10\\" \\"1 1\\"\""
```

**Comment by mcchong** [comment]
Cool, thanks.  That gets rid of the exception, but I'm still getting the following message:
`Zero Weights processed. Default weights will be used`

`+ java weka.classifiers.meta.MultiSearch -E PRC -t train.arff -W weka.classifiers.functions.LibSVM -d LibSVM.model -log-file log -search 'weka.core.setupgenerator.MathParameter -property cost -min -3 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.MathParameter -property gamma -min -2 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.ListParameter -property weights -list "\"1 100\" \"1 10\" \"1 1\""'
`

**Comment by fracpete** [comment]
It would be an error if you'd get this for each search evaluation. However, if you get it only once at the start, then this is simply due to the fact that Weka is setting an empty string (the default value) and LibSVM reports that it can't use those weights.
**BTW** I just released a new version of the plugin, since the `ListParameter` class had a bug in the `getOptions` method, returning the _list value_ instead of the _custom-delimiter value_ for the `-custom-delimiter` option. However, that doesn't affect you in this case, as you don't use a custom delimiter.
