### ISSUE TITLE
In weka Experimenter, MultiSearch raises 'java.lang.NullPointerException' 

### ISSUE THREAD

**Issue by krkhnh** [fracpete/multisearch-weka-package#4]
Weka version: `3.7.12`
multisearch version: `2015.9.2`

Error msg:

```
Running experiment: Runs from: 1 to: 1
Datasets: D:\Hans\CNTT\151001데이터마이닝\weka\06 기념일추가 징검다리휴일추가 월,주차추가\06.arff
Custom property iterator: on
Custom property path:
1  weka.experiment.RandomSplitResultProducer::splitEvaluator RegressionSplitEvaluator: weka.classifiers.rules.ZeroR (version 48055541465867954)
Custom property name:classifier
Custom property values:
 1 weka.classifiers.meta.MultiSearch No search performed yet.
ResultProducer: RandomSplitResultProducer: -P 80.0 -R -W weka.experiment.RegressionSplitEvaluator --: <null Instances>
ResultListener: weka.experiment.CSVResultListener@71c410e8

Writing experiment copy
Reading experiment copy
Made experiment copy
java.lang.NullPointerException
        weka.classifiers.meta.MultiSearch.enumerateMeasures(MultiSearch.java:926)
        weka.experiment.Experiment.determineAdditionalResultMeasures(Experiment.java:481)
        weka.experiment.Experiment.initialize(Experiment.java:429)
        weka.gui.experiment.RunPanel$ExperimentRunner.run(RunPanel.java:155)

        at weka.classifiers.meta.MultiSearch.enumerateMeasures(MultiSearch.java:926)
        at weka.experiment.Experiment.determineAdditionalResultMeasures(Experiment.java:481)
        at weka.experiment.Experiment.initialize(Experiment.java:429)
        at weka.gui.experiment.RunPanel$ExperimentRunner.run(RunPanel.java:155)
null
Done...
```

**Comment by fracpete** [comment]
Please post the command-line string of the MultiSearch classifier. Otherwise, it will be hard to figure out what went wrong.

**Comment by krkhnh** [comment]
command-line string of the MultiSearch: `weka.classifiers.meta.MultiSearch -E COMB -search "weka.core.setupgenerator.MathParameter -property classifier.ridge -min -10.0 -max -1.0 -step 1.0 -base 10.0 -expression pow(BASE,I)" -sample-size 100.0 -log-file "D:\\Program Files\\Weka-3-7" -initial-folds 2 -subsequent-folds 10 -num-slots 8 -S 1 -W weka.classifiers.functions.MLPRegressor -- -N 2 -R 0.01 -O 1.0E-6 -P 8 -E 8 -S 1`

Works on Explorer.

**Comment by fracpete** [comment]
Confirmed.

**Comment by fracpete** [comment]
Fixed. You can grab the new release v2015.10.15. NB: It requires Weka 3.7.13 now.
