### ISSUE TITLE
Support for one optimized parameter

### ISSUE THREAD

**Issue by kliegr** [fracpete/multisearch-weka-package#8]
If I try to use the package (via the Python wrapper) with one parameter:

```
    mparam = MathParameter()
    mparam.prop = "classifier.minBucketSize"
    mparam.minimum = 1
    mparam.maximum = 10
    mparam.step = 1
    mparam.expression = "I"     
    multi.parameters = [mparam]      
    multi.classifier = Classifier(classname"weka.classifiers.rules.OneR")      
```

I get the the following error:

```
            Exception in thread "Thread-0" java.lang.IllegalStateException: All points were already cached - abnormal state!
            at weka.classifiers.meta.MultiSearch.determineBestInSpace(MultiSearch.java:1336)
            at weka.classifiers.meta.MultiSearch.findBest(MultiSearch.java:1428)
            at weka.classifiers.meta.MultiSearch.buildClassifier(MultiSearch.java:1481)
```

If indeed the error I am getting is due to the number of parameters being 1,  I am not sure if one parameter optimization is not supported by design, or this is a bug.

In  case 2+ parameters are required, I think there could be some sort of illegal configuration error thrown earlier.

**Comment by fracpete** [comment]
Any number of parameters can be optimized. This error occurs when there is no better value located. All setups may result in same value for the chosen statistic.
